---
# a cronjob
- name: periodic-crawl
  command: ./ToolWatch/sync.sh
  image: python3.11
  schedule: "@daily"
  emails: onfailure
- name: special-restart-crawl
  command: ./ToolWatch/sync.sh
  image: python3.11